"""Dev/holdout assignment, the post-cutoff slice and minimum detectable effect (spec §4.3)."""

from __future__ import annotations

import hashlib
import math
import re
from collections import Counter
from collections.abc import Iterable
from statistics import NormalDist


def _u(key: str, seed: str) -> float:
    """Deterministic uniform [0,1) from an item id."""
    h = hashlib.sha256(f"{seed}:{key}".encode()).digest()
    return int.from_bytes(h[:8], "big") / 2**64


def norm_text(s: str) -> str:
    return re.sub(r"\W+", " ", s.lower()).strip()


def dedupe(items: Iterable[dict]) -> list[dict]:
    """Drop near-identical claims, preferring items with dates and rationales."""
    best: dict[str, dict] = {}
    for it in items:
        k = norm_text(it["text"])
        cur = best.get(k)
        score = (it.get("date") is not None, it.get("expert_rationale") is not None)
        if cur is None or score > (cur.get("date") is not None,
                                   cur.get("expert_rationale") is not None):
            best[k] = it
    return list(best.values())


def is_post_cutoff(item: dict, cutoff: str | None) -> bool:
    return bool(cutoff and item.get("date") and item["date"] > cutoff)


def assign(items: Iterable[dict], cutoff: str | None, seed: str = "cl-split-v1",
           holdout_frac: float = 0.62, post_cutoff_holdout_frac: float = 0.8) -> list[dict]:
    """Assign splits. Holdout gets expert-labeled items only (never crowd_labeled).

    holdout_frac 0.62 targets the spec ratio of ≥500 holdout to ≥300 dev.
    """
    out = []
    for it in items:
        it = dict(it)
        u = _u(it["id"], seed)
        if "crowd_labeled" in it.get("flags", []):
            it["split"] = "dev"
        elif is_post_cutoff(it, cutoff):
            it["split"] = "holdout" if u < post_cutoff_holdout_frac else "dev"
        else:
            it["split"] = "holdout" if u < holdout_frac else "dev"
        out.append(it)
    return out


def mde(n: int, discordance: float, alpha: float = 0.05, power: float = 0.8) -> float:
    """Minimum detectable accuracy difference for a paired comparison on n items.

    Paired difference d_i ∈ {-1,0,1}; under the null its variance ≈ discordance (share of
    items where the two protocols disagree on correctness). MDE = (z_{1-α/2}+z_power)·√(p/n).
    Macro-F1 behaves similarly but noisier, so treat this as a lower bound.
    """
    if n <= 0:
        return math.inf
    z = NormalDist().inv_cdf(1 - alpha / 2) + NormalDist().inv_cdf(power)
    return z * math.sqrt(discordance / n)


def report(items: list[dict], cutoff: str | None) -> str:
    by = Counter(it["split"] for it in items)
    lines = ["# Splits", "",
             "_Generated by `python -m lab.data.build`. Counts only; holdout content never "
             "enters the repo._", "",
             f"- Post-cutoff date: {cutoff or 'unknown (set knowledge_cutoff in models.yaml)'}",
             f"- Dev: {by['dev']} (target ≥ 300)", f"- Holdout: {by['holdout']} (target ≥ 500)"]
    post = [it for it in items if it["split"] == "holdout" and is_post_cutoff(it, cutoff)]
    lines.append(f"- Holdout post-cutoff slice: {len(post)}")
    lines += ["", "## By source and split", "", "| source | dev | holdout |", "|---|---|---|"]
    src = Counter((it.get("source", "?"), it["split"]) for it in items)
    for s in sorted({k[0] for k in src}):
        lines.append(f"| {s} | {src[(s, 'dev')]} | {src[(s, 'holdout')]} |")
    lines += ["", "## Gold label distribution", "", "| label | dev | holdout |", "|---|---|---|"]
    lab = Counter((it["gold"], it["split"]) for it in items)
    for g in sorted({k[0] for k in lab}):
        lines.append(f"| {g} | {lab[(g, 'dev')]} | {lab[(g, 'holdout')]} |")
    lines += ["", "## Minimum detectable effect (paired, α=0.05, power=0.8)", "",
              "Accuracy difference the holdout can detect, by how often two protocols differ "
              "in correctness:", "", "| discordance | full holdout | post-cutoff slice |",
              "|---|---|---|"]
    for p in (0.1, 0.2, 0.3):
        lines.append(f"| {p:.0%} | {mde(by['holdout'], p):.3f} | {mde(len(post), p):.3f} |")
    return "\n".join(lines) + "\n"
